spring:
  profiles:
    active: dev
  application:
    name: auth-service
  messages:
    basename: i18n/messages
    encoding : UTF-8
    always-use-message-format: false
    fallback-to-system-locale: true
    cache-seconds: -1

app:
  security:
    jwt:
      loginUrl: /login
      header: Authorization
      prefix: Bearer
      # accessToken expire in 24h,
      expiration: 86400000
      refresh:
        expiration: 8640000000000 #  refreshToken never expire 100 000 days
      secret: 0A7A690F19001C887DEB108AE40C54717E740385243437A863569C91BF8AC99B
  oauth2:
    authorizedRedirectUris: http://localhost:4200/oauth2/redirect, myandroidapp://oauth2/redirect, myiosapp://oauth2/redirect
  storage:
    root:
      directory: /media/rkouete/
    algorithm: hierarchical
  token:
    email:
      verification:
        duration: 3600000000
    password:
      reset:
        duration: 3600000000
    default:
      verification:
        duration: 3600000000
    refresh:
      duration: 259200000000