server:
  port: 9006
spring:
  application:
    name: es-evaluation services
  profiles:
    active: dev
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
