server:
  port: 9001
spring:
  application:
    name: zuul-gateway
  profiles:
    active: dev
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
zuul:
  sensitiveHeaders: Cookie,Set-Cookie

